### ISSUE TITLE
Does not pull in changes in referenced files?

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/modules.scuttlebutt.nz#7]
The changes I made to ssb-blobs don't seem to show. maybe it's the way the page is built?

**Comment by ahdinosaur** [comment]
hi @black-puppydog, yes the page is built using [netlify](https://www.netlify.com/) whenever there is a change to this git repo.

looks like i can create a build hook url that when POST'ed to, causes the page to rebuild.

now this should re-build the site:

```shell
curl -X POST -d {} https://api.netlify.com/build_hooks/5c122873bb7d27aab4307394
```

i could use another server i use for https redirects (so it's mostly idle) to run this in a cron job every hour.

okay, added an executable file on my Debian server at `/etc/cron.hourly/modules.scuttlebutt.nz`:

```shell
#!/bin/sh

curl -X POST -d {} https://api.netlify.com/build_hooks/5c122873bb7d27aab4307394
```

we'll see if this works! :smiley_cat:

**Comment by black-puppydog** [comment]
Looking good! :)
Plus, I just realized I made a stupid formatting mistake in ssb-blobs, so we'll see it in action shortly :D

**Comment by ahdinosaur** [comment]
as a note to myself, seems like the cron script wasn't working before, then i renamed it to `/etc/cron.hourly/module_scuttlebutt_nz` and now it seems to be working.
